services:
  - type: web
    name: cosmo-rlt-stats
    env: node
    nodeVersion: 18.17.0
    buildCommand: bash -c "cd backend && npm install && npm install --save-dev @types/pdfkit && npm run build"
    startCommand: bash -c "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 4001
    buildFilter:
      paths:
      - backend/**

  - type: web
    name: cosmo-rlt-stats-ui
    env: node
    nodeVersion: 18.17.0
    buildCommand: bash -c "cd frontend && npm install && npm run build && npm install -g serve"
    startCommand: bash -c "cd frontend && serve -s build -l 4000"
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://cosmo-rlt-stats.onrender.com
      - key: PORT
        value: 4000
    buildFilter:
      paths:
      - frontend/** 