services:
  - type: web
    name: cosmo-rlt-stats
    env: node
    nodeVersion: 18.17.0
    buildCommand: npm install && npm run build
    startCommand: npm run start:backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 4001
    buildFilter:
      paths:
      - backend/**

  - type: web
    name: cosmo-rlt-stats-ui
    env: node
    nodeVersion: 18.17.0
    buildCommand: npm install && npm run build
    startCommand: npm run start:frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://cosmo-rlt-stats.onrender.com
      - key: PORT
        value: 4000
    buildFilter:
      paths:
      - frontend/** 