services:
  - type: web
    name: cosmo-stats-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 4001
    buildFilter:
      paths:
      - backend/**
    rootDirectory: .

  - type: web
    name: cosmo-stats-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build && npm install -g serve
    startCommand: cd frontend && serve -s build -l 4000
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://cosmo-stats-backend.onrender.com
      - key: PORT
        value: 4000
    buildFilter:
      paths:
      - frontend/**
    rootDirectory: . 